sudo: required
dist: trusty
language: node_js
node_js:
  - "8"
install:
- yarn install
script:
- yarn run lint
- yarn run build:web
before_deploy:
- cp static/* dist/web/
- cd dist/web/
deploy:
  provider: heroku
  app: chatsggw
  skip_cleanup: true
  api_key:
    secure: "bf40941a-c3d4-4600-9ac1-e15d815790d1"
