environment:
  matrix:
    - node_version: "8"

cache:
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'

init:
  - git config --global core.autocrlf input

install:
  - yarn install --frozen-lockfile

build_script:
  - yarn build:pc

test: off
